### ISSUE TITLE
"prefix" config value gets incorrectly overwritten with "git-annex"

### ISSUE THREAD

**Issue by Idealcoder** [DanielDent/git-annex-remote-rclone#33]
I had a rclone special remote called "blue", which worked flawlessly for several years until it broke, with error message:

```
remote currently unavailable or git-annex-remote-rclone failed to parse rclone output
```
Debugging showed this plugin trying to access a bucket called "git-annex", which did 
not exist as my bucket was called "blue".

Setting the prefix back to the correct value fixed it.

```
$ git annex enableremote bluewhale prefix=blue
```

I have not been able to reproduce this bug again, but it seems occasionally "prefix" value gets overwritten with "git-annex".

**Comment by joeyh** [comment]
I had a look at the code for git-annex-remote-rclone and I don't think it can change the prefix on its own. 

Then I had a look at git-annex, and found its commit 6a91471923566bbd7cbfa292a3bc63420b5e5dd9, which fixed a bug that broke GETCONFIG. With GETCONFIG broken, git-annex-remote-rclone would, on enableremote, call GETCONFIG, get nothing back, and default the prefix to "git-annex", rather than the previously stored prefix, storing that back with SETCONFIG.

That explains the bug, and the time frame of that reversion matches up to when this bug was filed. Since it's fixed in git-annex, I recommend closing this.

**Comment by Idealcoder** [comment]
Thanks. Great to know this is fixed!

**Comment by yarikoptic** [comment]
"describe-git-annex" bot speaking here: the 6a91471923566bbd7cbfa292a3bc63420b5e5dd9 is AKA [8.20200226-148-g6a9147192 AKA 8.20200309~24](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=6a91471923566bbd7cbfa292a3bc63420b5e5dd9)
